import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');process.chdir(root);
const config=JSON.parse(fs.readFileSync('release.json'));
const out=path.resolve('build',config.version,'components/app/cloudcli');
fs.mkdirSync(out,{recursive:true});
for(const dir of ['dist','dist-server','public'])fs.cpSync('cloudcli/'+dir,path.join(out,dir),{recursive:true});
fs.cpSync('custom',path.join(out,'dist-server'),{recursive:true});
fs.copyFileSync('cloudcli/package.json',path.join(out,'package.json'));
for(const file of ['LICENSE','NOTICE'])if(fs.existsSync('cloudcli/'+file))fs.copyFileSync('cloudcli/'+file,path.join(out,file));
const update=fs.readFileSync('ui/update.js','utf8').replaceAll('__BIGA_VERSION__',config.version);
let html=fs.readFileSync('ui/index.html','utf8').replace('id="buildVersion">v21','id="buildVersion">'+config.version).replace('<title>','<title>BigaCli · ');
html=html.replace('</body>','<script>'+update+'</script></body>');
for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
fs.writeFileSync(path.join(out,'dist/index.html'),html);
fs.copyFileSync('launcher.cjs',path.join(out,'../launcher.cjs'));
fs.writeFileSync(path.join(out,'../version.json'),JSON.stringify(config,null,2));
for(const rel of fs.readdirSync('custom',{recursive:true}).filter(f=>f.endsWith('.js')))execFileSync(process.execPath,['--check',path.resolve('custom',rel)]);
console.log('Built BigaCli '+config.version);
