import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');process.chdir(root);
const config=JSON.parse(fs.readFileSync('release.json'));
const out=path.resolve('build',config.version,'components/app/cloudcli');
const require=createRequire(path.resolve('cloudcli/package.json'));
fs.mkdirSync(out,{recursive:true});
for(const dir of ['dist','dist-server','public'])fs.cpSync('cloudcli/'+dir,path.join(out,dir),{recursive:true});
fs.cpSync('custom',path.join(out,'dist-server'),{recursive:true});
fs.copyFileSync('docs/BIGACLI_AGENT_RULES.md',path.join(out,'dist-server/server/modules/bigacli/BIGACLI_AGENT_RULES.md'));
fs.copyFileSync('cloudcli/package.json',path.join(out,'package.json'));
fs.cpSync('ui/vendor',path.join(out,'dist/vendor'),{recursive:true});
fs.copyFileSync('ui/preview-ui.js',path.join(out,'dist/preview-ui.js'));
fs.writeFileSync(path.join(out,'dist/i18n.js'),'window.BIGA_TRANSLATIONS='+fs.readFileSync('ui/locales.json','utf8')+';\n'+fs.readFileSync('ui/i18n.js','utf8'));
for(const file of ['LICENSE','NOTICE'])if(fs.existsSync('cloudcli/'+file))fs.copyFileSync('cloudcli/'+file,path.join(out,file));
const update=fs.readFileSync('ui/update.js','utf8').replaceAll('__BIGA_VERSION__',config.version).replace('__BIGA_RELEASE_NOTES__',JSON.stringify(JSON.parse(fs.readFileSync('releases/update-notes.json','utf8'))).replaceAll('<','\\u003c'));
let html=fs.readFileSync('ui/index.html','utf8').replace('id="buildVersion">v21','id="buildVersion">'+config.version).replace('<title>','<title>BigaCli · ');
await require('esbuild').build({entryPoints:['ui/markdown.jsx'],bundle:true,format:'iife',globalName:'BigaMarkdown',platform:'browser',minify:true,nodePaths:[path.resolve('cloudcli/node_modules')],define:{'process.env.NODE_ENV':'"production"'},outfile:path.join(out,'dist/biga-markdown.js')});
await require('esbuild').build({entryPoints:['cloudcli/src/modules/chat/utils/searchTargetLocator.ts'],bundle:true,format:'iife',globalName:'BigaSearch',platform:'browser',minify:true,outfile:path.join(out,'dist/biga-search.js')});
const markdownHash=createHash('sha256').update(fs.readFileSync(path.join(out,'dist/biga-markdown.js'))).digest('hex').slice(0,12);
html=html.replace('<script>',`<script src="/biga-markdown.js?v=${markdownHash}"></script><script>`);
html=html.replace('</body>','<script>'+update+'</script></body>');
for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
fs.writeFileSync(path.join(out,'dist/index.html'),html);
fs.copyFileSync('launcher.cjs',path.join(out,'../launcher.cjs'));
fs.writeFileSync(path.join(out,'../version.json'),JSON.stringify(config,null,2));
for(const rel of fs.readdirSync('custom',{recursive:true}).filter(f=>f.endsWith('.js')))execFileSync(process.execPath,['--check',path.resolve('custom',rel)]);
console.log('Built BigaCli '+config.version);
