const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {spawn}=require('node:child_process');
const version=JSON.parse(fs.readFileSync('release.json')).version;
const root=path.resolve(`build/${version}/components/app/cloudcli/dist`);
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'biga-ui-'));
const fixture=`<script>
(async()=>{let count=0;const check=(ok,name)=>{if(!ok)throw Error(name);count++};try{
check(!localStorage.getItem('cloudcli_token_v2'),'fresh browser without token');
check(!$('loginBtn')&&!$('registerBtn'),'no web account forms');
check(window.bigaRequests.some(p=>new URL(p,location.origin).pathname==='/api/projects'),'projects requested automatically without login: '+JSON.stringify(window.bigaErrors));
check(!wsUrl().includes('token='),'WebSocket needs no token');
const savedApi=api;
api=async()=>({phase:'idle',version:'0.2.1',available:null,error:'test network failure'});
await bigaStatus('check');check($('toast').textContent.includes('检查更新失败'),'check failure shown distinctly');
api=async()=>({phase:'idle',version:'0.2.1',available:null,error:null});
await bigaStatus('check');check($('toast').textContent==='已是最新版本','latest shown only after successful check');
api=savedApi;
const originalProjects=allProjects,originalProject=currentProject,originalOpen=openRecentSession,originalLoadProjects=loadProjects;
allProjects=[{id:'new-project',name:'测试项目',path:'C:/work/test'},{id:'second-project',name:'测试项目',path:'C:/work/second'}];currentProject=allProjects[0];renderProjectTree();
check($('projectTree').querySelectorAll('.projectHeader').length===2,'projects stay separate');
const oldWorkspacePaths=workspacePaths;workspacePaths=new Set(['C:/work/test']);renderProjectTree();
check($('projectTree').querySelectorAll(':scope > .mother').length===1&&$('projectTree').querySelector('.legacyProjects .mother'),'managed workspace separated from history');
check(!$('projectTree').querySelector('.legacyProjects').open,'old projects start collapsed');
check(!$('projectTree').querySelector('.motherBtn').textContent.includes('C:/'),'folder path removed from main tree');
$('projectTree').querySelector('.projectMore').click();check(!$('projectTree').querySelector('.projectMenu').classList.contains('hidden'),'workspace actions expand');
workspacePaths=oldWorkspacePaths;
let createdPayload=null,openedSession=null;
api=async(path,options)=>{check(path==='/api/providers/sessions','reuse CloudCLI create endpoint');createdPayload=JSON.parse(options.body);return {sessionId:'new-session',sessionName:'新对话'}};
loadProjects=async()=>{};openRecentSession=async session=>{openedSession=session};await createConversation(allProjects[0],$('projectTree').querySelector('.projectNew'));
check(createdPayload.provider==='codex'&&createdPayload.projectPath==='C:/work/test'&&openedSession.id==='new-session','create and open native conversation');
api=savedApi;allProjects=originalProjects;currentProject=originalProject;openRecentSession=originalOpen;loadProjects=originalLoadProjects;
clearChat();closeDrawer();
check(getComputedStyle($('chat')).overscrollBehaviorY==='none','chat edge has no overscroll stretch');
check(getComputedStyle(document.body).position==='fixed','document cannot scroll behind keyboard');
const originalHeight=document.documentElement.style.getPropertyValue('--app-height');
document.documentElement.style.setProperty('--app-height','340px');
const oldViewport=window.visualViewport;Object.defineProperty(window,'visualViewport',{configurable:true,value:{height:340}});
$('input').value=Array(40).fill('长输入换行').join('\\n');resizeComposerInput();
check(document.querySelector('.composer').getBoundingClientRect().bottom<=341,'long composer fits keyboard viewport');
check($('input').scrollHeight>$('input').clientHeight,'long input scrolls internally');
Object.defineProperty(window,'visualViewport',{configurable:true,value:oldViewport});document.documentElement.style.setProperty('--app-height',originalHeight);$('input').value='';resizeComposerInput();
const originalLocation=location.href,restoreApi=api,restoreOpen=openRecentSession;let restored=null;
history.replaceState(null,'','/session/restore-test');api=async path=>{check(path==='/api/providers/sessions/restore-test','restore uses native session details');return {sessionId:'restore-test',provider:'codex'}};
openRecentSession=async session=>{restored=session.sessionId};await restoreCurrentConversation();check(restored==='restore-test','restore conversation from URL');
api=restoreApi;openRecentSession=restoreOpen;history.replaceState(null,'',originalLocation);
renderHistoryMessage({kind:'text',role:'user',content:'历史用户输入'});
handleEvent({kind:'status',text:'正在压缩上下文'});
check($('chat').querySelector('.processSummary').textContent.startsWith('正在压缩上下文'),'native compaction status displayed');
setProcessing(true,'Working');
check($('chat').querySelector('.processSummary').textContent.startsWith('正在压缩上下文'),'other activity does not clear compaction status');
handleEvent({kind:'status',text:'正在处理'});
check($('chat').querySelector('.processSummary').textContent.startsWith('正在处理'),'compaction completion restores processing');
check(getComputedStyle($('chat').querySelector('.bubble')).fontSize==='16px','body text is 16px');
check($('chat').querySelectorAll('.msg.user').length===1,'user history renders');
renderMessageStream({itemId:'progress-test',messageKind:'text',content:'正在检查',phase:'commentary'});
check(!!$('chat').querySelector('.processGroup .commentary'),'first delta uses grouped commentary style');
renderMessageStream({itemId:'progress-test',messageKind:'text',content:'中'});
check($('chat').querySelectorAll('.processGroup .commentary').length===1,'phase preserved across deltas');
renderMessageStream({itemId:'progress-test',messageKind:'text',content:'正在检查中',phase:'commentary'},true);
const savedHistory=loadHistory;let historyReloads=0;loadHistory=()=>{historyReloads++};
handleEvent({kind:'complete',exitCode:0});await new Promise(r=>setTimeout(r,650));
check(historyReloads===0&&$('chat').querySelector('.msg.user'),'completion preserves user message without history reload');loadHistory=savedHistory;
check($('chat').querySelector('.processGroup .processSummary').textContent==='已完成思考过程（1 步）','completed process count');
toggleProcessDetails($('chat').querySelector('.processDrawer'),true);
check($('chat').querySelector('.processSteps .messageTime'),'process step timestamp');
const processDetails=$('chat').querySelector('.processDrawer'),steps=processDetails.querySelector('.processSteps');
check(getComputedStyle(steps).overflowY==='clip','process area does not capture scrolling');
check(getComputedStyle(steps.querySelector('.bubble')).fontSize==='15px','process text reduced to 15px');
toggleProcessDetails(processDetails,false);toggleProcessDetails(processDetails,true);
check(getComputedStyle(processDetails.querySelector('.processFold')).transitionProperty==='grid-template-rows','CSS drawer only changes size');
check(processDetails.classList.contains('expanded')&&!processDetails.querySelector('.processFold').inert,'rapid toggle ends expanded');
check(!$('chat').querySelector('.processGroup > .messageMeta'),'no outer timestamp above process');
addAssistant('最终回复','',undefined,'final_answer');
check($('chat').lastElementChild.querySelector('.messageMeta .messageTime'),'final timestamp above final bubble');
const stamp=document.createElement('div');stamp.innerHTML=messageStamp(new Date());check(!stamp.textContent.includes('/'),'today time only');
const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);stamp.innerHTML=messageStamp(yesterday);check(stamp.textContent.includes('/'),'older message date');
selectSettingsTab('general');check(!$('generalPanel').classList.contains('hidden'),'general settings tab');
$('themeSelect').value='dark';$('themeSelect').dispatchEvent(new Event('change'));
check(getComputedStyle(document.documentElement).colorScheme==='dark'&&localStorage.getItem('bigacli-theme')==='dark','dark theme and saved preference');
$('themeSelect').value='light';$('themeSelect').dispatchEvent(new Event('change'));
const clipboard=new DataTransfer();clipboard.items.add(new File([new Uint8Array([137,80,78,71])],'paste.png',{type:'image/png'}));
$('input').dispatchEvent(new ClipboardEvent('paste',{clipboardData:clipboard,cancelable:true}));
check(pendingFiles.length===1&&$('attachmentList').querySelector('img'),'paste uses image attachment preview');
$('attachmentList').querySelector('.removeAttachment').click();check(pendingFiles.length===0,'pasted image removable');
check(getComputedStyle(document.querySelector('.composerStatus svg')).width==='18px','smaller status icons');
if(innerWidth>=900){check(getComputedStyle($('drawer')).visibility==='visible','desktop sidebar visible');check(document.querySelector('.app').getBoundingClientRect().left===280,'desktop chat beside sidebar')}
else check(getComputedStyle($('drawer')).visibility==='hidden','mobile drawer closed');
clearChat();
const table='| 问题 | 结论 |\\n|---|---|\\n| **模型** | Astra |\\n| 速度 | 普通 |';
setProcessing(true);check($('sendBtn').getAttribute('aria-label')==='停止生成'&&$('chat').querySelector('.processGroup.active'),'processing indicator and stop button');
renderMessageStream({itemId:'animation-test',content:'**完成**',phase:'final_answer'});
check($('chat').querySelector('.assistant.streaming')&&!$('chat').querySelector('.processGroup.active'),'thinking transitions to streaming reply');
renderMessageStream({itemId:'animation-test',content:'**完成**',phase:'final_answer'},true);setProcessing(false);
check($('chat').querySelectorAll('.copyActions button').length===2&&!$('chat').querySelector('.assistant.streaming'),'copy actions after generation');
check($('chat').querySelectorAll('.copyActions svg').length===2&&$('chat').querySelectorAll('.copyActions button')[1].textContent==='复制为TXT','reference copy labels and SVG icons');
const originalCopy=copyText;let copiedReply='';copyText=async text=>{copiedReply=text;return true};
$('input').disabled=false;$('input').value='保留草稿';$('input').focus();$('input').setSelectionRange(2,2);
const copyButton=$('chat').querySelector('.copyActions button');
const press=new PointerEvent('pointerdown',{bubbles:true,cancelable:true});copyButton.dispatchEvent(press);
check(press.defaultPrevented&&document.activeElement===$('input'),'copy pointer preserves input focus');
$('chat').querySelector('.copyActions button').click();await Promise.resolve();check(copiedReply==='**完成**','MD copies original source');
$('chat').querySelectorAll('.copyActions button')[1].click();await Promise.resolve();check(copiedReply==='完成','TXT copies rendered text');copyText=originalCopy;
const secureDescriptor=Object.getOwnPropertyDescriptor(window,'isSecureContext'),originalExec=document.execCommand;let fallbackText='';
Object.defineProperty(window,'isSecureContext',{configurable:true,value:false});document.execCommand=()=>{fallbackText=$('input').value;return true};
await copyText('复制内容');check(fallbackText==='复制内容'&&$('input').value==='保留草稿'&&$('input').selectionStart===2&&document.activeElement===$('input'),'HTTP copy preserves draft caret and focus');
document.execCommand=originalExec;Object.defineProperty(window,'isSecureContext',secureDescriptor);$('input').value='';
check($('sendBtn').getAttribute('aria-label')==='发送消息','send button restored after completion');
clearChat();
addAssistant(table);check($('chat').querySelectorAll('tbody tr').length===2,'GFM table');check(!!$('chat').querySelector('td strong'),'inline formatting');
addAssistant('<img src=x onerror=alert(1)>');check(!$('chat').querySelector('img'),'HTML escaped');
addAssistant('[危险](javascript:alert(1))');check(!$('chat').querySelector('a[href^="javascript:"]'),'unsafe URL blocked');
addAssistant('[报告](C:/work/report.md)');check($('chat').querySelector('.file-link[data-file="C:/work/report.md"]'),'workspace link preserved');
renderMessageStream({itemId:'table-stream',content:'| A | B |\\n|---|---|\\n'});renderMessageStream({itemId:'table-stream',content:'| 1 | 2 |'});check($('chat').querySelectorAll('table').length===2,'stream table');
renderMessageStream({itemId:'table-stream',content:'| A | B |\\n|---|---|\\n| 1 | 2 |',phase:'final_answer'},true);check($('chat').querySelectorAll('table').length===2,'no duplicate final');
currentSession={id:'ui-test'};currentProvider='codex';currentModel='gpt-6-astra';providerModels={OPTIONS:[{value:currentModel,label:'GPT-6 Astra',serviceTiers:[{id:'priority'}],effort:{values:[{value:'low'},{value:'ultra'}]}}]};fillModelSelect();fillEffortSelect();fillSpeedSelect();
check($('speedSelect').value==='default','ordinary by default');check(sendOptions().serviceTier==='default','explicit ordinary send');
$('speedSelect').value='priority';$('speedSelect').dispatchEvent(new Event('change'));check(sendOptions().serviceTier==='priority','fast send');check($('speedPicker').querySelector('summary').title.includes('快速'),'fast in general settings');fillSpeedSelect();check($('speedSelect').value==='priority','session preference restored');
currentSession={id:'another-session'};fillSpeedSelect();check($('speedSelect').value==='default','new session ordinary');
providerModels.OPTIONS[0].serviceTiers=[];fillSpeedSelect();check($('speedSelect').options[1].disabled,'unsupported fast disabled');
check($('speedSelect').closest('#speedPicker')&&!$('modelPicker').contains($('speedSelect')),'speed moved out of model picker');
$('modelSelect').disabled=false;$('effortSelect').disabled=false;syncComposerLabels();
setComposerPicker($('modelPicker'),true);await new Promise(r=>requestAnimationFrame(r));
check($('modelChoices').querySelector('button').textContent==='GPT-6 Astra','dynamic model choices');
const entry=$('modelPicker').querySelector('summary').getBoundingClientRect(),panel=$('modelPicker').querySelector('.pickerPanel'),rect=panel.getBoundingClientRect();
check(Math.abs(parseFloat(panel.style.transformOrigin)-(entry.left+entry.width/2-parseFloat(panel.style.left)))<1,'animation originates at entry');
check(parseFloat(panel.style.left)>=0&&parseFloat(panel.style.left)+panel.offsetWidth<=innerWidth,'popup fits viewport');
$('effortChoices').querySelector('button').click();check($('modelPicker').open,'effort selection keeps popup open');
$('modelChoices').querySelector('button').click();await $('modelPicker').popupAnimation.finished;await new Promise(r=>requestAnimationFrame(r));check(!$('modelPicker').open,'model selection closes popup');
setComposerPicker($('permissionPicker'),true);await new Promise(r=>requestAnimationFrame(r));
check($('permissionPicker').querySelector('.pickerPanel').style.transformOrigin!==panel.style.transformOrigin,'different entry has its own origin');
closeComposerPickers();
const savedUsage=loadUsageData;loadUsageData=()=>{};openUsagePopup();
const usagePanel=$('usageBox').querySelector('.usageModal');
check(!!usagePanel.popupAnimation&&usagePanel.style.transformOrigin&&getComputedStyle(usagePanel).borderRadius==='18px','quota shares anchored popup animation and style');
closeUsagePopup();await usagePanel.popupAnimation.finished;await new Promise(r=>requestAnimationFrame(r));
check($('usageBox').classList.contains('hidden'),'quota closes after animation');loadUsageData=savedUsage;
check(document.documentElement.scrollWidth<=innerWidth,'no page horizontal overflow');check(getComputedStyle($('chat').querySelector('.tableScroll')).overflowX==='auto','table horizontal scroll');
document.body.dataset.testResult='PASS '+count;document.body.dataset.testError='';
}catch(e){document.body.dataset.testResult='FAIL';document.body.dataset.testError=e.message}fetch('/result',{method:'POST',body:JSON.stringify({result:document.body.dataset.testResult,error:document.body.dataset.testError})})})();
</script>`;
const capture='<script>localStorage.clear();window.bigaErrors=[];window.addEventListener("error",e=>window.bigaErrors.push(e.message));window.bigaRequests=[];const originalFetch=window.fetch;window.fetch=(url,options)=>{window.bigaRequests.push(String(url));return originalFetch(url,options)};</script>';
const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('<head>','<head>'+capture).replace('</body>',fixture+'</body>');
let completed=false;
const watchdog=setTimeout(()=>{if(!completed){console.error('Browser checks timed out');process.exitCode=1;server.close()}},30000);
const server=http.createServer((req,res)=>{if(req.url==='/result'){let body='';req.on('data',b=>body+=b);req.on('end',()=>{const result=JSON.parse(body);completed=true;clearTimeout(watchdog);console.log(result);if(!result.result.startsWith('PASS'))process.exitCode=1;res.end('ok');setTimeout(()=>server.close(),3000)});return}if(req.url==='/biga-markdown.js'){res.setHeader('Content-Type','application/javascript');res.end(fs.readFileSync(path.join(root,'biga-markdown.js')))}else{res.setHeader('Content-Type','text/html');res.end(html)}});
server.listen(3194,'127.0.0.1',()=>{
 const edge=process.env.EDGE_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
 const p=spawn(edge,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--user-data-dir='+path.join(temp,'profile'),'--window-size='+(process.env.UI_WINDOW_SIZE||'500,900'),'--virtual-time-budget=2500','--dump-dom','--screenshot='+path.join(temp,'ui.png'),'http://127.0.0.1:3194'],{windowsHide:true});
 p.stdout.resume();p.stderr.resume();p.on('error',e=>{console.error(e);process.exitCode=1;clearTimeout(watchdog);server.close()});console.log('Screenshot: '+path.join(temp,'ui.png'));
});
